---
title: "Group-26 AAD-Assignment-2"
author: "Omar, Eloise, Alina, Sue"
date: '`r Sys.Date()`'
output:
  pdf_document:
    toc: true
    toc_depth: 4
    number_sections: false
    fig_width: 8
    fig_height: 6
    keep_tex: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      dev = "png",
                      dpi = 150)

# Load relevant libraries
library(dplyr)
library(ggplot2)
```

# 2.1 Nonlinear model vs non-parametric model

\noindent \large \textbf{GAM:} \normalsize

\noindent \textbf{Pros}
\begin{itemize}
  \item \textbf{Flexibility to capture non-linearity}. In a GAMM we replace each linear term $\beta_{k} x_{k}$ with a smooth function $f_{k}(x_{k})$,     meaning we can automatically 
  \item 456
\end{itemize}

\noindent \textbf{Cons}
\begin{itemize}
  \item 123
  \item 456
\end{itemize}

\noindent \large \textbf{KNN:} \normalsize

\noindent \textbf{Pros}
\begin{itemize}
  \item 123
  \item 456
\end{itemize}

\noindent \textbf{Cons}
\begin{itemize}
  \item 123
  \item 456
\end{itemize}


## 2.1.1 GAM vs KNN approach

## 2.1.2 GAM vs KNN Regression Model

## 2.1.3 Which model performs better?

# 2.2 Classification models

## 2.2.1 Two classification methods

## 2.2.2 Suggested classifiers

## 2.2.3 Which classification method performs better?

# 2.3 A hybrid approach

## 2.3.1 Dicussing feasibility of the approach

## 2.3.2 test MSE of medianHousingValue using the approach

## 2.3.3 Comparison of the accuracy of this procedure to model in 2.1.3


